### ISSUE TITLE
top bottom layers bug?

### ISSUE THREAD

**Issue by MagnusThome** [phnxdrgn536/FLSun-v400#12]
I suppose the "Top Layers" should really be automated too as the "Bottom Layers"

Secondly I think 1,2mm is a bit much but that's only my personal opinion :-)

![image](https://user-images.githubusercontent.com/32169384/211493140-3fc8cb08-ec63-45e4-932d-361aae7cecec.png)

**Comment by lloydpick** [comment]
I agree that 8 bottom layers is bit much, would be good to get this lowered to a maximum of 5

**Comment by phnxdrgn536** [comment]
what material is this profile using? you might have an outdated version of the profiles. i am constantly updating and tweaking them. currently the only profiles with 1.2 mm top/bottom are the engineering profiles to which you would want the thicker setting. everything else is 1mm and 0.8mm. Please make sure you download the most recent version of files.

**Comment by MagnusThome** [comment]
Will test the newer setup
