### ISSUE TITLE
BAT file failed on Windows 11 two disk setup

### ISSUE THREAD

**Issue by cjshaker** [phnxdrgn536/FLSun-v400#14]
In D:\Tmp, on Windows 11, I ran load_V400_profiles_V5.2_STOCK_Firmware.BAT as system administrator. It failed with the following errors:

D:\Tmp>load_V400_profiles_V5.2_STOCK_Firmware.bat

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2   && md meshes

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\meshes   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400.stl )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\definitions   && (curl -o flsun_v400.def.json https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_STOCK.def.json )
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     53      0 --:--:-- --:--:-- --:--:--    54

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\extruders   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_extruder/flsun_v400_extruder_0.def.json )
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     54      0 --:--:-- --:--:-- --:--:--    54

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\intent   && md PETG PLA

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\intent\PETG   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Draft_Print_Quick.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Fast_Print_Accurate.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Fast_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_High_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Normal_Quality_Accurate.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_Normal_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PETG/flsun_v400_0.4_PETG_VeryDraft_Print_Quick.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\intent\PLA   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Draft_Print_Quick.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Fast_Print_Accurate.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Fast_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_High_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Normal_Quality_Accurate.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_Normal_Visual.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_intent/PLA/flsun_v400_0.4_PLA_VeryDraft_Print_Quick.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality   && md ABS PETG PLA
A subdirectory or file PETG already exists.
Error occurred while processing: PETG.
A subdirectory or file PLA already exists.
Error occurred while processing: PLA.

D:\Tmp>curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_Draft_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_Fast_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_Normal_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_Superdraft_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/flsun_v400_global_Verydraft_Quality.inst.cfg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     55      0 --:--:-- --:--:-- --:--:--    56
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     57      0 --:--:-- --:--:-- --:--:--    57
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     70      0 --:--:-- --:--:-- --:--:--    70
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     82      0 --:--:-- --:--:-- --:--:--    82
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     69      0 --:--:-- --:--:-- --:--:--    69
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     86      0 --:--:-- --:--:-- --:--:--    86

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\ABS   && md 0.25 0.4 0.6 0.8
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\ABS\0.25   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.25/flsun_v400_0.25_ABS_Normal_Quality.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\ABS\0.4   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.4/flsun_v400_0.4_ABS_Draft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.4/flsun_v400_0.4_ABS_Fast_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.4/flsun_v400_0.4_ABS_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.4/flsun_v400_0.4_ABS_Normal_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.4/flsun_v400_0.4_ABS_VeryDraft_Print.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\ABS\0.6   && (curl -O  https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.6/flsun_v400_0.6_ABS_Fast_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.6/flsun_v400_0.6_ABS_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.6/flsun_v400_0.6_ABS_Normal_Quality.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\ABS\0.8   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.8/flsun_v400_0.8_ABS_Draft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.8/flsun_v400_0.8_ABS_Verydraft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/ABS/0.8/flsun_v400_0.8_ABS_Superdraft_Print.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PETG   && md 0.25 0.4 0.6 0.8
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PETG\0.4   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PETG/0.4/flsun_v400_0.4_ABS_Draft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PETG/0.4/flsun_v400_0.4_ABS_Fast_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PETG/0.4/flsun_v400_0.4_ABS_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PETG/0.4/flsun_v400_0.4_ABS_Normal_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PETG/0.4/flsun_v400_0.4_ABS_VeryDraft_Print.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PLA   && md 0.25 0.4 0.6 0.8
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PLA\0.25   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.25/flsun_v400_0.25_PLA_Normal_Quality.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PLA\0.4   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.4/flsun_v400_0.4_PLA_Draft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.4/flsun_v400_0.4_PLA_Fast_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.4/flsun_v400_0.4_PLA_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.4/flsun_v400_0.4_PLA_Normal_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.4/flsun_v400_0.4_PLA_VeryDraft_Print.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PLA\0.6   && (curl -O  https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.6/flsun_v400_0.6_PLA_Fast_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.6/flsun_v400_0.6_PLA_High_Quality.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.6/flsun_v400_0.6_PLA_Normal_Quality.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\quality\PLA\0.8   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.8/flsun_v400_0.8_PLA_Draft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.8/flsun_v400_0.8_PLA_Verydraft_Print.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_quality/PLA/0.8/flsun_v400_0.8_PLA_Superdraft_Print.inst.cfg )
The system cannot find the path specified.

D:\Tmp>cd C:\Users\Admin\AppData\Roaming\cura\5.2\variants   && (curl -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_variants/flsun_v400_0.25.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_variants/flsun_v400_0.4.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_variants/flsun_v400_0.6.inst.cfg -O https://raw.githubusercontent.com/phnxdrgn536/FLSun-v400/main/cura/flsun_v400_variants/flsun_v400_0.8.inst.cfg )
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     37      0 --:--:-- --:--:-- --:--:--    37
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     78      0 --:--:-- --:--:-- --:--:--    78
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     81      0 --:--:-- --:--:-- --:--:--    81
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     84      0 --:--:-- --:--:-- --:--:--    84

D:\Tmp>start "" "C:\Program Files\Ultimaker Cura 5.2.1\ultimaker-cura.exe"

D:\Tmp>

**Comment by phnxdrgn536** [comment]
This bat file no longer functions. it has been replaced by CPL (Cura profile Loader) download the .zip file from here [https://github.com/phnxdrgn536/FLSun-v400/raw/main/Cura%20Profile%20Loader.zip](url) unzip and run the .exe... it workes with any Cura 5.x version.

**Comment by cjshaker** [comment]
That sounds great. Will try it now
Thank you!
Chris Shaker
