### ISSUE TITLE
MAC Profile Loader Folder Path Issue

### ISSUE THREAD

**Issue by arshish1612** [phnxdrgn536/FLSun-v400#33]
Ive tried the mac Profile loader multiple times & ensured that there are no previous printers installed.

The issue seems to be that on a MAC it creates a **single** folder with a name as follows "quality\PETG\0.4" rather than creating a subfolder for PETG & 0.4
![Screenshot 2023-03-19 at 8 17 05 PM](https://user-images.githubusercontent.com/8477844/226183836-16062be4-7da6-49f2-86a7-cd6739378578.png)

If I manually copy the files instead of using the loader it works

**Comment by phnxdrgn536** [comment]
Yes this is correct, there is an issue with the Mac loader but
unfortunately I’m not able to correct it easily. I don’t have a Mac to be
able to test the functions of the loader on and I’ve been looking for
someone that has Mac programming experience to help out. Right now you
should just be able to correct the file structure issue and place the files
in the correct locations to be able to run them.

**Comment by arshish1612** [comment]
You may want to call this out in your documentation.
