### ISSUE TITLE
Profiles not showing up

### ISSUE THREAD

**Issue by abrahamabel** [phnxdrgn536/FLSun-v400#4]
I noticed that the Cura profile for my printer is showing an empty field under the nozzle section, but I actually have four nozzle profiles saved in the inst.cfg format in the variants folder. Is there a way to resolve this discrepancy and access the nozzle profiles that I have saved?

**Comment by phnxdrgn536** [comment]
can you upload some screenshots? also did you load the "quality" files into the proper folder. Without them nothing will show up

**Comment by dhu77** [comment]
Hello
First, thank you for the good work! and sharing it.
I also have the same problem, here are some print screen

thank you
David
![Capture d’écran 2023-01-04 232111](https://user-images.githubusercontent.com/77931866/210661840-fe660564-e5f2-439f-8397-0053578e93a4.png)
![Capture d’écran 2023-01-04 232347](https://user-images.githubusercontent.com/77931866/210661844-7f2d20b0-9dec-40d4-a2fb-c5915e393904.png)

**Comment by phnxdrgn536** [comment]
did you copy the "variant" files to the proper folder as well as replace the printer definition file? 
![variant](https://user-images.githubusercontent.com/120244371/210663482-02e659a3-4fbd-4960-9f51-aa45e3f91f46.png)
![definition](https://user-images.githubusercontent.com/120244371/210663486-591d6cd2-e33f-41c5-ab6f-a374e91493b0.png)

**Comment by phnxdrgn536** [comment]
Found the issue... when i added the two separate definitions for stock or updated firmware everything else is looking for flsun_v400.def.json. Simply remove the printer you have already added (you may have to add a random printer to allow this) and then close cura, rename the printer definition file to flsun_v400.def.json, and then reopen cura and add the v400 back and everything will show correctly.

**Comment by dhu77** [comment]
it works

thank you
