### ISSUE TITLE
Retract question

### ISSUE THREAD

**Issue by voidmodular** [phnxdrgn536/FLSun-v400#5]
I installed these but the retract seems excessive at 6.5.    Curious if I messed up the install or this is something I should change manually on them.  I rolled back the install and deleted any v400 references in the configuration folder then reinstalled them just to make sure I followed directions.

![image](https://user-images.githubusercontent.com/54509893/210821913-56234f76-8088-495c-9189-451ef37b0b4e.png)

**Comment by voidmodular** [comment]
I tried this in both Cura 5.2 and 5.3 Alpha, retracts are 6.5 in both.

**Comment by phnxdrgn536** [comment]
This is a known issue. go ahead and change it manually for now. i will adjust the default values for this today and push an update to replace the profiles.

**Comment by voidmodular** [comment]
Excellent! Thanks!  Just wanted to be sure it wasn't something I did.

**Comment by phnxdrgn536** [comment]
retractions have  been updated
