### ISSUE TITLE
No profiles matching this extruder

### ISSUE THREAD

**Issue by voidmodular** [phnxdrgn536/FLSun-v400#6]
Wanted to check if I did something wrong here as well.  I get "no profiles matching this extruder" when I select materials.

![image](https://user-images.githubusercontent.com/54509893/210828292-3c806d5f-f8e0-45e6-ac6d-6543b6d44a88.png)

**Comment by checc0** [comment]
Same for me, Started from a clean installation of Cura 5.2.1.

**Comment by phnxdrgn536** [comment]
This was a known issue and has been addressed, remove the V400 you added in the cura program, rename the definition file to flsun_v400.def.json, and re-add the printer to cura. All the dependencies for the nozzles and profiles are looking for flsun_v400 not the _stock or _updated_firmware the two files are named.
